### ISSUE TITLE
Mason Graham Slideshow of Features

### ISSUE THREAD

**Issue by MasonG31** [CSAllenISD/2023-ISP-unIQue#16]
Make a slide show involving the potential features of the interactive webpage. Share with colleagues.

**Comment by SophieH8** [comment]
This is a good idea, and will help us plan out our webpage more thoroughly.

**Comment by FarazPir** [comment]
I think this will help get our ideas out and make our project more planned. This way our idea will be less vague.

**Comment by Mehak-J** [comment]
A slideshow sounds like a great way to help us visualize and understand all the features we need.
