### ISSUE TITLE
Make an HTML Page

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#23]
Make an HTML Page for the homepage for UnIQue.

**Comment by a-sane-human-being** [comment]
i think we've already started with this now

**Comment by MasonG31** [comment]
This is very important and will be the medium for our project. I am looking forward to having the working page, and we can have the progress achieved on a physical piece of evidence.

**Comment by Delikatessen** [comment]
This is pretty vague, so I'm closing it. We should make specific issues for each department's HTML.
