### ISSUE TITLE
Make a Stylesheet

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#24]
Make a .css file for the homepage and possibly other pages.

**Comment by a-sane-human-being** [comment]
i forgot about that. it's going to be really long after we finish the project

**Comment by Delikatessen** [comment]
we should include some subtle animations, I use them on my DP and it's really pleasing to look at. They can be a bit complicated, but ChatGPT can explain how to set them up really well. I'll also link the W3 Schools article on them.

[W3 CSS Anims](https://www.w3schools.com/css/css3_animations.asp)

**Comment by MasonG31** [comment]
I think this is a great idea but is less important as of right now when compared with the coding of the website. But, making the website look nice and adding stylistic points is never a bad idea. We can slowly look at W3 examples of this, and at other colleagues' Digital Portfolios.

**Comment by Delikatessen** [comment]
Very vague issue, let's split it up by site section/department.
