### ISSUE TITLE
Design html page

### ISSUE THREAD

**Issue by SophieH8** [CSAllenISD/2023-ISP-unIQue#26]
Begin designing the Html page to make it look neat like an actual website.

**Comment by MasonG31** [comment]
Sounds great, I'm glad we decided on doing an HTML page instead of trying Javascript. I don't think we have enough time to neatly code a javascript webpage, so I think it is a safer bet to do HTML. We have a large group, and we have many digital portfolios to take examples from. Looks good

**Comment by Delikatessen** [comment]
Also pretty vague, we should make specific issues for each department/section's CSS pages.

**Comment by MasonG31** [comment]
Yes, let's make sure all of our issues are very extremely specific so that we now exactly what needs to be done and not have one-hundred vague tasks.
