### ISSUE TITLE
Mason Graham Research Ways to Raise IQ and Brain Health.

### ISSUE THREAD

**Issue by MasonG31** [CSAllenISD/2023-ISP-unIQue#29]
I am going to research on a document ways to raise IQ and improve brain health.

**Comment by SterbenShell** [comment]
This will be very important going forward because this will be the backbone of our project. This will go into play with our games and other parts of the project.

**Comment by SophieH8** [comment]
It is very important that we use reliable sources for our research.

**Comment by MasonG31** [comment]
I want our website to be strongly anchored on credible facts and logic, rather than just making stuff up and throwing it on a website. I want our project to look professional and actually have a practical use, in a neutral way I believe that a strong number of our colleague's projects are lacking this factor. If we're going to spend time coding, building, and working on our interactive website, then why ruin that by making it unreliable and incorrect information?

**Comment by FarazPir** [comment]
@MasonG31 I agree with this, I think a good way to ensure this is to make sure we have a place where we cite our sources.

**Comment by MasonG31** [comment]
Yes, I totally forgot about that, thanks. I will make a sheet of sources so that our data looks much more reliable than just words on a page. It will be credible and trustable.

**Comment by MasonG31** [comment]
I have postponed my doing the brain research because of falling behind on in-class missions and due dates. My goal for the week is to finish both missions, so that next week I can use the majority of my time for researching brain health and IQ data, which will be the backbone of our data.
