### ISSUE TITLE
Create Help Tree Template

### ISSUE THREAD

**Issue by Delikatessen** [CSAllenISD/2023-ISP-unIQue#34]
The Help Tree should be modular, it's gonna be a HUGE pain if we make each layer hard-coded. We should start by making a help tree template that we can freely modify.

**Comment by MasonG31** [comment]
Sounds great, I think moving away from the Chatbot is a great idea, and will save us time. I'm all for working smarter and not harder, let's avoid hard-coding at all costs. As for the complexity of the help tree, I would like it to not appear as a glorified if elif else branch of code. But I recognize that we don't have the time to make a complex chat bot, so let's find a happy medium in between. Thanks, Mason.

**Comment by MasonG31** [comment]
Looking into the help tree, after ChatGTP has been widely used, would our help tree/chatbot have any value that chatgtp doesn't have? I think if we want this to be valuable it needs to be friendly, and have a higher knowledge of these emotions than the AI. I'm brainstorming ways to make our help tree more valuable.

**Comment by Delikatessen** [comment]
The Help Tree's template should be shared with everyone on the Help Tree team in Google Drive.
