### ISSUE TITLE
Github Pages Access

### ISSUE THREAD

**Issue by Delikatessen** [CSAllenISD/2023-ISP-unIQue#36]
We don't have access to the tab in Github that lets you turn your repo into github pages, I'll ask ben-yaakov if we can have access to this, because that's definitely going to be the easiest way to get unIQue online. If not I'll find a work around.

**Comment by MasonG31** [comment]
This would be great, giving us more control over our page. Using the GitHub project manager is new to many people in our class, including me, so understanding how to use the system more would be very efficient for our group.

**Comment by Delikatessen** [comment]
We got it! :)
