### ISSUE TITLE
Make Avertisment

### ISSUE THREAD

**Issue by MasonG31** [CSAllenISD/2023-ISP-unIQue#40]

**Comment by MasonG31** [comment]
This advertisement will be featured on our ISP MVP project, and it is important that we make it presentable and look nice. On the side, from a confidence standpoint, it would be great if our is the best in the class. I believe that the work that we are doing is to a high standard, and high-standard work deserves a high-standard advertisement.

**Comment by FarazPir** [comment]
The advertisement is looking great, I think it's ready to be presented!

**Comment by MasonG31** [comment]
This was completed, we went with Sophie's design instead of the one I made on Canava. I think it's great that we have two alternate designs, maybe we can implement these in the future.
