### ISSUE TITLE
Make game prototypes

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#44]
Make functional prototypes for javaScript games. These prototypes will make it easy for the games to be implemented into the website.

**Comment by MasonG31** [comment]
Looking through games that help with IQ, are brain games with words, such as anagrams or a word hunt, and then sudoku.  A memory game would also work, as these have been proved to help with brain help. I think if we did a word-based game, a number-based game, and then a graphic-based matching game that would be a good variety, while also having the content we need.

**Comment by Delikatessen** [comment]
We already have an issue for the matching game, #43 . Let's make individual issues for the others. Issues should be specific, otherwise they're kind of meaningless "buzz-issues".

**Comment by MasonG31** [comment]
I agree 100 percent, each issue should be specific and not be able to have more issues come from that one issue. Just from an organizational sound point. Looks good.
