### ISSUE TITLE
Have JavaScript Embedded in the website

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#45]
Make it so not only is the JavaScript code called in the HTML file but it has some interaction with the page. For example, have it to where it makes an area for the game on the page.

**Comment by MasonG31** [comment]
Yes I think that this is the best way to do this. Instead of making the entire file java, if we only made the game parts Java, or the parts we need to be Java. I think that we are great in HTML and limiting the amount of Javascript we have to write is a great idea. Sounds great, Mason Graham

**Comment by Delikatessen** [comment]
Way too vague of an issue, y'all.
