### ISSUE TITLE
Have naviagable webpages

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#46]
Have multiple webpages that are all navigable between each other.

**Comment by MasonG31** [comment]
Sounds great, we have about 3 different aspects for our interactive webpage, and it would be a nice stylistic touch if they were separate and navigable, unlike just a long Wikipedia page. I don't think this will be a large challenge for our team.

**Comment by MasonG31** [comment]
I have recently checked on the matching game, and the webpage is navagalibe to and looks like a standard page. This is a great step in the process of building our web pages, and I am very excited to see how the others turn out as well.

**Comment by hgiordano888** [comment]
Completed basic webpage connections
