### ISSUE TITLE
Sliding Puzzle Game

### ISSUE THREAD

**Issue by SophieH8** [CSAllenISD/2023-ISP-unIQue#54]
Create a prototype for the sliding puzzle game. Have a randomization button to randomize number locations.Squares my only move to the empty slot when clicked.

**Comment by MasonG31** [comment]
This sounds great, I have seen multiple people in this computer science class playing this during the week, meaning that it is already a popular game and that it would be played If it was on our interactive webpage. I will say, with the limited time I don't know if we can create all 3 of the games, and we will have to talk about which games are our top priority, so we can have a conservative plan A before we start planning the other games.
