### ISSUE TITLE
Word Scramble Game

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#55]
Make a game where you have to unscramble a word in 30 seconds.

**Comment by MasonG31** [comment]
This sounds straight outta Game Pidegon, which will work perfectly with our audience. I have seen from my own experience how captivating these word games can be, and how popular they can be with the high school crowd. Pair this with the research that we did in which word games are great for raising the problem-solving and reading part of the brain, and we have a perfect addition to our webpage.

**Comment by Delikatessen** [comment]
Functional, available at https://csallenisd.github.io/2023-ISP-unIQue/Game-Prototypes/scramble.html

Further CSS and formatting may be necessary, closing completion issue.
