### ISSUE TITLE
Brainstorm games

### ISSUE THREAD

**Issue by FarazPir** [CSAllenISD/2023-ISP-unIQue#65]
Continue to brainstorm and research more games until we've reached a point where we don't want to add any more games.
This will ensure that we have a good library of games to keep our users engaged and increase their IQ.

**Comment by Delikatessen** [comment]
We've exhausted a lot of the low hanging fruit, but some more I can think of are games such as Sudoku, Hangman, Crossword, Jigsaw, Tetris, Mahjong, Kakuro, Nonograms, Word Search, Sokoban, and Boggle.

I tried to make crossword earlier, but it was hell to program. If someone else wants to try tackling that, feel free. I think I'm going to self assign myself Tetris and Word Search? I feel I could do those with relative ease.

**Comment by FarazPir** [comment]
This week me (@FarazPir)  and @SterbenShell will be brainstorming the last two games. I think we have reached a point where we definitely have enough games for our games library and after these last two games, we will have seven games which will be more than enough for our games library.

**Comment by SterbenShell** [comment]
Three new Issues that could be implemented include number hunt, minesweeper, and 2048. 

Number hunt - a game that gives you multiple numbers and you have to find the sum to gain points.

Minesweeper - you are given a board where you have to find all the squares that do not contain a mine, and flag the ones that do have mines. Squares without mines have a number on them indicating the amount of mine squares it is directly touching, including diagonally. Your first click on the board will randomly generate a cluster of non-mine squares for you to work around.

2048 - You are given a 4x4 board starting with two squares with the values of 2. Every time you make a move, in which you either click the up, down, left, or right arrow(or w,a,s,d), you shift all the squares on the board to the direction of the key you clicked to the furthest slot that can be filled. Also, a new square is generated on a empty square randomly and can contain the numbers 2,4, or 8. If two squares have the same value and are on the same column or row, will push together to form 1 square with the two values added together. You lose if you make a move causing all the slots to fill up. The goal is to try to get to the point where one of the squares on the board becomes the value: 2048.

**Comment by FarazPir** [comment]
We have enough games brainstormed now.
