### ISSUE TITLE
Make the White Noise Page More Cozy

### ISSUE THREAD

**Issue by Delikatessen** [CSAllenISD/2023-ISP-unIQue#73]
Add elements to the White Noise page that makes it feel less corporate;
      Add Anime Girl
      Redesign CSS for Coziness
      Add some relaxing visual effects to the page

**Comment by a-sane-human-being** [comment]
yes

**Comment by Delikatessen** [comment]
yes

**Comment by Delikatessen** [comment]
Changes finished! I absolutely LOVE the result.
